/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xmodelica.modelica.ModelicaPackage#getAnnotation()
 * @model
 * @generated
 */
public interface Annotation extends Comment
{
} // Annotation
