/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arithmetic Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.ArithmeticExpression#getOps <em>Ops</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getArithmeticExpression()
 * @model
 * @generated
 */
public interface ArithmeticExpression extends Relation
{
  /**
   * Returns the value of the '<em><b>Ops</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ops</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ops</em>' attribute list.
   * @see xmodelica.modelica.ModelicaPackage#getArithmeticExpression_Ops()
   * @model unique="false"
   * @generated
   */
  EList<String> getOps();

} // ArithmeticExpression
