/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.ClassSpecifier#getMod <em>Mod</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getClassSpecifier()
 * @model
 * @generated
 */
public interface ClassSpecifier extends ClassDefinition
{
  /**
   * Returns the value of the '<em><b>Mod</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mod</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mod</em>' containment reference.
   * @see #setMod(ClassModification)
   * @see xmodelica.modelica.ModelicaPackage#getClassSpecifier_Mod()
   * @model containment="true"
   * @generated
   */
  ClassModification getMod();

  /**
   * Sets the value of the '{@link xmodelica.modelica.ClassSpecifier#getMod <em>Mod</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mod</em>' containment reference.
   * @see #getMod()
   * @generated
   */
  void setMod(ClassModification value);

} // ClassSpecifier
