/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Declaration1</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xmodelica.modelica.ModelicaPackage#getComponentDeclaration1()
 * @model
 * @generated
 */
public interface ComponentDeclaration1 extends ComponentClause1
{
} // ComponentDeclaration1
