/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Redeclaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xmodelica.modelica.ModelicaPackage#getElementRedeclaration()
 * @model
 * @generated
 */
public interface ElementRedeclaration extends Argument
{
} // ElementRedeclaration
