/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Replaceable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.ElementReplaceable#getConst <em>Const</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getElementReplaceable()
 * @model
 * @generated
 */
public interface ElementReplaceable extends ElementModicationOrReplaceable, ElementRedeclaration
{
  /**
   * Returns the value of the '<em><b>Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Const</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const</em>' containment reference.
   * @see #setConst(ConstrainingClause)
   * @see xmodelica.modelica.ModelicaPackage#getElementReplaceable_Const()
   * @model containment="true"
   * @generated
   */
  ConstrainingClause getConst();

  /**
   * Sets the value of the '{@link xmodelica.modelica.ElementReplaceable#getConst <em>Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const</em>' containment reference.
   * @see #getConst()
   * @generated
   */
  void setConst(ConstrainingClause value);

} // ElementReplaceable
