/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.ElementList#getElem <em>Elem</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getElementList()
 * @model
 * @generated
 */
public interface ElementList extends EObject
{
  /**
   * Returns the value of the '<em><b>Elem</b></em>' containment reference list.
   * The list contents are of type {@link xmodelica.modelica.Element}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elem</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elem</em>' containment reference list.
   * @see xmodelica.modelica.ModelicaPackage#getElementList_Elem()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElem();

} // ElementList
