/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call Args</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.FunctionCallArgs#getRes <em>Res</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getFunctionCallArgs()
 * @model
 * @generated
 */
public interface FunctionCallArgs extends EObject
{
  /**
   * Returns the value of the '<em><b>Res</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Res</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Res</em>' containment reference.
   * @see #setRes(FunctionArguments)
   * @see xmodelica.modelica.ModelicaPackage#getFunctionCallArgs_Res()
   * @model containment="true"
   * @generated
   */
  FunctionArguments getRes();

  /**
   * Sets the value of the '{@link xmodelica.modelica.FunctionCallArgs#getRes <em>Res</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Res</em>' containment reference.
   * @see #getRes()
   * @generated
   */
  void setRes(FunctionArguments value);

} // FunctionCallArgs
