/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Factor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.LogicalFactor#getFactors <em>Factors</em>}</li>
 *   <li>{@link xmodelica.modelica.LogicalFactor#isNot <em>Not</em>}</li>
 *   <li>{@link xmodelica.modelica.LogicalFactor#getRel <em>Rel</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getLogicalFactor()
 * @model
 * @generated
 */
public interface LogicalFactor extends LogicalTerm
{
  /**
   * Returns the value of the '<em><b>Factors</b></em>' containment reference list.
   * The list contents are of type {@link xmodelica.modelica.LogicalFactor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Factors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Factors</em>' containment reference list.
   * @see xmodelica.modelica.ModelicaPackage#getLogicalFactor_Factors()
   * @model containment="true"
   * @generated
   */
  EList<LogicalFactor> getFactors();

  /**
   * Returns the value of the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Not</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not</em>' attribute.
   * @see #setNot(boolean)
   * @see xmodelica.modelica.ModelicaPackage#getLogicalFactor_Not()
   * @model
   * @generated
   */
  boolean isNot();

  /**
   * Sets the value of the '{@link xmodelica.modelica.LogicalFactor#isNot <em>Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not</em>' attribute.
   * @see #isNot()
   * @generated
   */
  void setNot(boolean value);

  /**
   * Returns the value of the '<em><b>Rel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rel</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rel</em>' containment reference.
   * @see #setRel(Relation)
   * @see xmodelica.modelica.ModelicaPackage#getLogicalFactor_Rel()
   * @model containment="true"
   * @generated
   */
  Relation getRel();

  /**
   * Sets the value of the '{@link xmodelica.modelica.LogicalFactor#getRel <em>Rel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rel</em>' containment reference.
   * @see #getRel()
   * @generated
   */
  void setRel(Relation value);

} // LogicalFactor
