/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.LogicalExpression#getTerms <em>Terms</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getLogicalExpression()
 * @model
 * @generated
 */
public interface LogicalExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Terms</b></em>' containment reference list.
   * The list contents are of type {@link xmodelica.modelica.LogicalTerm}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Terms</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Terms</em>' containment reference list.
   * @see xmodelica.modelica.ModelicaPackage#getLogicalExpression_Terms()
   * @model containment="true"
   * @generated
   */
  EList<LogicalTerm> getTerms();

} // LogicalExpression
