/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xmodelica.modelica.ModelicaPackage#getLogicalTerm()
 * @model
 * @generated
 */
public interface LogicalTerm extends LogicalExpression
{
} // LogicalTerm
