/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.Negation#getNeg_op <em>Neg op</em>}</li>
 *   <li>{@link xmodelica.modelica.Negation#getTerm <em>Term</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getNegation()
 * @model
 * @generated
 */
public interface Negation extends ArithmeticExpression
{
  /**
   * Returns the value of the '<em><b>Neg op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Neg op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neg op</em>' attribute.
   * @see #setNeg_op(String)
   * @see xmodelica.modelica.ModelicaPackage#getNegation_Neg_op()
   * @model
   * @generated
   */
  String getNeg_op();

  /**
   * Sets the value of the '{@link xmodelica.modelica.Negation#getNeg_op <em>Neg op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neg op</em>' attribute.
   * @see #getNeg_op()
   * @generated
   */
  void setNeg_op(String value);

  /**
   * Returns the value of the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Term</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' containment reference.
   * @see #setTerm(Term)
   * @see xmodelica.modelica.ModelicaPackage#getNegation_Term()
   * @model containment="true"
   * @generated
   */
  Term getTerm();

  /**
   * Sets the value of the '{@link xmodelica.modelica.Negation#getTerm <em>Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Term</em>' containment reference.
   * @see #getTerm()
   * @generated
   */
  void setTerm(Term value);

} // Negation
