/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Expression List</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xmodelica.modelica.ModelicaPackage#getOutputExpressionList()
 * @model
 * @generated
 */
public interface OutputExpressionList extends EObject
{
} // OutputExpressionList
