/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Short Class Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.ShortClassDefinition#getMode <em>Mode</em>}</li>
 *   <li>{@link xmodelica.modelica.ShortClassDefinition#getComment <em>Comment</em>}</li>
 *   <li>{@link xmodelica.modelica.ShortClassDefinition#getList <em>List</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getShortClassDefinition()
 * @model
 * @generated
 */
public interface ShortClassDefinition extends ElementRedeclaration, ElementReplaceable
{
  /**
   * Returns the value of the '<em><b>Mode</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mode</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mode</em>' containment reference.
   * @see #setMode(ClassModification)
   * @see xmodelica.modelica.ModelicaPackage#getShortClassDefinition_Mode()
   * @model containment="true"
   * @generated
   */
  ClassModification getMode();

  /**
   * Sets the value of the '{@link xmodelica.modelica.ShortClassDefinition#getMode <em>Mode</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mode</em>' containment reference.
   * @see #getMode()
   * @generated
   */
  void setMode(ClassModification value);

  /**
   * Returns the value of the '<em><b>Comment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comment</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' containment reference.
   * @see #setComment(Comment)
   * @see xmodelica.modelica.ModelicaPackage#getShortClassDefinition_Comment()
   * @model containment="true"
   * @generated
   */
  Comment getComment();

  /**
   * Sets the value of the '{@link xmodelica.modelica.ShortClassDefinition#getComment <em>Comment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' containment reference.
   * @see #getComment()
   * @generated
   */
  void setComment(Comment value);

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(EnumList)
   * @see xmodelica.modelica.ModelicaPackage#getShortClassDefinition_List()
   * @model containment="true"
   * @generated
   */
  EnumList getList();

  /**
   * Sets the value of the '{@link xmodelica.modelica.ShortClassDefinition#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(EnumList value);

} // ShortClassDefinition
