/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stored Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.StoredDefinition#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @see xmodelica.modelica.ModelicaPackage#getStoredDefinition()
 * @model
 * @generated
 */
public interface StoredDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link xmodelica.modelica.ClassDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see xmodelica.modelica.ModelicaPackage#getStoredDefinition_Classes()
   * @model containment="true"
   * @generated
   */
  EList<ClassDefinition> getClasses();

} // StoredDefinition
