/*
 * generated by Xtext 2.9.2
 */
package xmodelica.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import xmodelica.ui.internal.XmodelicaActivator;

public class ModelicaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XmodelicaActivator.getInstance().getInjector("xmodelica.Modelica");
	}

}
