/**
 * generated by Xtext 2.9.2
 */
package xmodelica.validation;

import xmodelica.validation.AbstractModelicaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ModelicaValidator extends AbstractModelicaValidator {
}
