/**
 * generated by Xtext 2.9.2
 */
package xmodelica.ui.contentassist;

import xmodelica.ui.contentassist.AbstractModelicaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ModelicaProposalProvider extends AbstractModelicaProposalProvider {
}
