/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xmodelica.modelica.ArraySubscripts;
import xmodelica.modelica.ClassDefinition;
import xmodelica.modelica.ClassModification;
import xmodelica.modelica.Composition;
import xmodelica.modelica.ModelicaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Class Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#isFinal <em>Final</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#isEncapsulated <em>Encapsulated</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#getName <em>Name</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#getStr_comment <em>Str comment</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#getComposition <em>Composition</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#getName_end <em>Name end</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#getName2 <em>Name2</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#getSubs <em>Subs</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ClassDefinitionImpl#getMod <em>Mod</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClassDefinitionImpl extends ElementImpl implements ClassDefinition
{
  /**
   * The default value of the '{@link #isFinal() <em>Final</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFinal()
   * @generated
   * @ordered
   */
  protected static final boolean FINAL_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isFinal() <em>Final</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFinal()
   * @generated
   * @ordered
   */
  protected boolean final_ = FINAL_EDEFAULT;

  /**
   * The default value of the '{@link #isEncapsulated() <em>Encapsulated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEncapsulated()
   * @generated
   * @ordered
   */
  protected static final boolean ENCAPSULATED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isEncapsulated() <em>Encapsulated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEncapsulated()
   * @generated
   * @ordered
   */
  protected boolean encapsulated = ENCAPSULATED_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getStr_comment() <em>Str comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr_comment()
   * @generated
   * @ordered
   */
  protected static final String STR_COMMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStr_comment() <em>Str comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr_comment()
   * @generated
   * @ordered
   */
  protected String str_comment = STR_COMMENT_EDEFAULT;

  /**
   * The cached value of the '{@link #getComposition() <em>Composition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComposition()
   * @generated
   * @ordered
   */
  protected Composition composition;

  /**
   * The default value of the '{@link #getName_end() <em>Name end</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName_end()
   * @generated
   * @ordered
   */
  protected static final String NAME_END_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName_end() <em>Name end</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName_end()
   * @generated
   * @ordered
   */
  protected String name_end = NAME_END_EDEFAULT;

  /**
   * The default value of the '{@link #getPrefix() <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefix()
   * @generated
   * @ordered
   */
  protected static final String PREFIX_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrefix() <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefix()
   * @generated
   * @ordered
   */
  protected String prefix = PREFIX_EDEFAULT;

  /**
   * The default value of the '{@link #getName2() <em>Name2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName2()
   * @generated
   * @ordered
   */
  protected static final String NAME2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName2() <em>Name2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName2()
   * @generated
   * @ordered
   */
  protected String name2 = NAME2_EDEFAULT;

  /**
   * The cached value of the '{@link #getSubs() <em>Subs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubs()
   * @generated
   * @ordered
   */
  protected ArraySubscripts subs;

  /**
   * The cached value of the '{@link #getMod() <em>Mod</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMod()
   * @generated
   * @ordered
   */
  protected ClassModification mod;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClassDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelicaPackage.Literals.CLASS_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isFinal()
  {
    return final_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFinal(boolean newFinal)
  {
    boolean oldFinal = final_;
    final_ = newFinal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__FINAL, oldFinal, final_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isEncapsulated()
  {
    return encapsulated;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEncapsulated(boolean newEncapsulated)
  {
    boolean oldEncapsulated = encapsulated;
    encapsulated = newEncapsulated;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__ENCAPSULATED, oldEncapsulated, encapsulated));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStr_comment()
  {
    return str_comment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStr_comment(String newStr_comment)
  {
    String oldStr_comment = str_comment;
    str_comment = newStr_comment;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__STR_COMMENT, oldStr_comment, str_comment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Composition getComposition()
  {
    return composition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetComposition(Composition newComposition, NotificationChain msgs)
  {
    Composition oldComposition = composition;
    composition = newComposition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__COMPOSITION, oldComposition, newComposition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setComposition(Composition newComposition)
  {
    if (newComposition != composition)
    {
      NotificationChain msgs = null;
      if (composition != null)
        msgs = ((InternalEObject)composition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.CLASS_DEFINITION__COMPOSITION, null, msgs);
      if (newComposition != null)
        msgs = ((InternalEObject)newComposition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.CLASS_DEFINITION__COMPOSITION, null, msgs);
      msgs = basicSetComposition(newComposition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__COMPOSITION, newComposition, newComposition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName_end()
  {
    return name_end;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName_end(String newName_end)
  {
    String oldName_end = name_end;
    name_end = newName_end;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__NAME_END, oldName_end, name_end));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPrefix()
  {
    return prefix;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrefix(String newPrefix)
  {
    String oldPrefix = prefix;
    prefix = newPrefix;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__PREFIX, oldPrefix, prefix));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName2()
  {
    return name2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName2(String newName2)
  {
    String oldName2 = name2;
    name2 = newName2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__NAME2, oldName2, name2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ArraySubscripts getSubs()
  {
    return subs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSubs(ArraySubscripts newSubs, NotificationChain msgs)
  {
    ArraySubscripts oldSubs = subs;
    subs = newSubs;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__SUBS, oldSubs, newSubs);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSubs(ArraySubscripts newSubs)
  {
    if (newSubs != subs)
    {
      NotificationChain msgs = null;
      if (subs != null)
        msgs = ((InternalEObject)subs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.CLASS_DEFINITION__SUBS, null, msgs);
      if (newSubs != null)
        msgs = ((InternalEObject)newSubs).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.CLASS_DEFINITION__SUBS, null, msgs);
      msgs = basicSetSubs(newSubs, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__SUBS, newSubs, newSubs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassModification getMod()
  {
    return mod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMod(ClassModification newMod, NotificationChain msgs)
  {
    ClassModification oldMod = mod;
    mod = newMod;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__MOD, oldMod, newMod);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMod(ClassModification newMod)
  {
    if (newMod != mod)
    {
      NotificationChain msgs = null;
      if (mod != null)
        msgs = ((InternalEObject)mod).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.CLASS_DEFINITION__MOD, null, msgs);
      if (newMod != null)
        msgs = ((InternalEObject)newMod).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.CLASS_DEFINITION__MOD, null, msgs);
      msgs = basicSetMod(newMod, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.CLASS_DEFINITION__MOD, newMod, newMod));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ModelicaPackage.CLASS_DEFINITION__COMPOSITION:
        return basicSetComposition(null, msgs);
      case ModelicaPackage.CLASS_DEFINITION__SUBS:
        return basicSetSubs(null, msgs);
      case ModelicaPackage.CLASS_DEFINITION__MOD:
        return basicSetMod(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ModelicaPackage.CLASS_DEFINITION__FINAL:
        return isFinal();
      case ModelicaPackage.CLASS_DEFINITION__ENCAPSULATED:
        return isEncapsulated();
      case ModelicaPackage.CLASS_DEFINITION__NAME:
        return getName();
      case ModelicaPackage.CLASS_DEFINITION__STR_COMMENT:
        return getStr_comment();
      case ModelicaPackage.CLASS_DEFINITION__COMPOSITION:
        return getComposition();
      case ModelicaPackage.CLASS_DEFINITION__NAME_END:
        return getName_end();
      case ModelicaPackage.CLASS_DEFINITION__PREFIX:
        return getPrefix();
      case ModelicaPackage.CLASS_DEFINITION__NAME2:
        return getName2();
      case ModelicaPackage.CLASS_DEFINITION__SUBS:
        return getSubs();
      case ModelicaPackage.CLASS_DEFINITION__MOD:
        return getMod();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ModelicaPackage.CLASS_DEFINITION__FINAL:
        setFinal((Boolean)newValue);
        return;
      case ModelicaPackage.CLASS_DEFINITION__ENCAPSULATED:
        setEncapsulated((Boolean)newValue);
        return;
      case ModelicaPackage.CLASS_DEFINITION__NAME:
        setName((String)newValue);
        return;
      case ModelicaPackage.CLASS_DEFINITION__STR_COMMENT:
        setStr_comment((String)newValue);
        return;
      case ModelicaPackage.CLASS_DEFINITION__COMPOSITION:
        setComposition((Composition)newValue);
        return;
      case ModelicaPackage.CLASS_DEFINITION__NAME_END:
        setName_end((String)newValue);
        return;
      case ModelicaPackage.CLASS_DEFINITION__PREFIX:
        setPrefix((String)newValue);
        return;
      case ModelicaPackage.CLASS_DEFINITION__NAME2:
        setName2((String)newValue);
        return;
      case ModelicaPackage.CLASS_DEFINITION__SUBS:
        setSubs((ArraySubscripts)newValue);
        return;
      case ModelicaPackage.CLASS_DEFINITION__MOD:
        setMod((ClassModification)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ModelicaPackage.CLASS_DEFINITION__FINAL:
        setFinal(FINAL_EDEFAULT);
        return;
      case ModelicaPackage.CLASS_DEFINITION__ENCAPSULATED:
        setEncapsulated(ENCAPSULATED_EDEFAULT);
        return;
      case ModelicaPackage.CLASS_DEFINITION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ModelicaPackage.CLASS_DEFINITION__STR_COMMENT:
        setStr_comment(STR_COMMENT_EDEFAULT);
        return;
      case ModelicaPackage.CLASS_DEFINITION__COMPOSITION:
        setComposition((Composition)null);
        return;
      case ModelicaPackage.CLASS_DEFINITION__NAME_END:
        setName_end(NAME_END_EDEFAULT);
        return;
      case ModelicaPackage.CLASS_DEFINITION__PREFIX:
        setPrefix(PREFIX_EDEFAULT);
        return;
      case ModelicaPackage.CLASS_DEFINITION__NAME2:
        setName2(NAME2_EDEFAULT);
        return;
      case ModelicaPackage.CLASS_DEFINITION__SUBS:
        setSubs((ArraySubscripts)null);
        return;
      case ModelicaPackage.CLASS_DEFINITION__MOD:
        setMod((ClassModification)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ModelicaPackage.CLASS_DEFINITION__FINAL:
        return final_ != FINAL_EDEFAULT;
      case ModelicaPackage.CLASS_DEFINITION__ENCAPSULATED:
        return encapsulated != ENCAPSULATED_EDEFAULT;
      case ModelicaPackage.CLASS_DEFINITION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ModelicaPackage.CLASS_DEFINITION__STR_COMMENT:
        return STR_COMMENT_EDEFAULT == null ? str_comment != null : !STR_COMMENT_EDEFAULT.equals(str_comment);
      case ModelicaPackage.CLASS_DEFINITION__COMPOSITION:
        return composition != null;
      case ModelicaPackage.CLASS_DEFINITION__NAME_END:
        return NAME_END_EDEFAULT == null ? name_end != null : !NAME_END_EDEFAULT.equals(name_end);
      case ModelicaPackage.CLASS_DEFINITION__PREFIX:
        return PREFIX_EDEFAULT == null ? prefix != null : !PREFIX_EDEFAULT.equals(prefix);
      case ModelicaPackage.CLASS_DEFINITION__NAME2:
        return NAME2_EDEFAULT == null ? name2 != null : !NAME2_EDEFAULT.equals(name2);
      case ModelicaPackage.CLASS_DEFINITION__SUBS:
        return subs != null;
      case ModelicaPackage.CLASS_DEFINITION__MOD:
        return mod != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (final: ");
    result.append(final_);
    result.append(", encapsulated: ");
    result.append(encapsulated);
    result.append(", name: ");
    result.append(name);
    result.append(", str_comment: ");
    result.append(str_comment);
    result.append(", name_end: ");
    result.append(name_end);
    result.append(", prefix: ");
    result.append(prefix);
    result.append(", name2: ");
    result.append(name2);
    result.append(')');
    return result.toString();
  }

} //ClassDefinitionImpl
