/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xmodelica.modelica.ArraySubscripts;
import xmodelica.modelica.ComponentClause;
import xmodelica.modelica.ComponentList;
import xmodelica.modelica.ModelicaPackage;
import xmodelica.modelica.TypeSpecifier;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Component Clause</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xmodelica.modelica.impl.ComponentClauseImpl#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ComponentClauseImpl#getType <em>Type</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ComponentClauseImpl#getSubs <em>Subs</em>}</li>
 *   <li>{@link xmodelica.modelica.impl.ComponentClauseImpl#getComps <em>Comps</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComponentClauseImpl extends ElementImpl implements ComponentClause
{
  /**
   * The default value of the '{@link #getPrefix() <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefix()
   * @generated
   * @ordered
   */
  protected static final String PREFIX_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrefix() <em>Prefix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrefix()
   * @generated
   * @ordered
   */
  protected String prefix = PREFIX_EDEFAULT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected TypeSpecifier type;

  /**
   * The cached value of the '{@link #getSubs() <em>Subs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubs()
   * @generated
   * @ordered
   */
  protected ArraySubscripts subs;

  /**
   * The cached value of the '{@link #getComps() <em>Comps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComps()
   * @generated
   * @ordered
   */
  protected ComponentList comps;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComponentClauseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelicaPackage.Literals.COMPONENT_CLAUSE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPrefix()
  {
    return prefix;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrefix(String newPrefix)
  {
    String oldPrefix = prefix;
    prefix = newPrefix;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.COMPONENT_CLAUSE__PREFIX, oldPrefix, prefix));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeSpecifier getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(TypeSpecifier newType, NotificationChain msgs)
  {
    TypeSpecifier oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaPackage.COMPONENT_CLAUSE__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(TypeSpecifier newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.COMPONENT_CLAUSE__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.COMPONENT_CLAUSE__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.COMPONENT_CLAUSE__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ArraySubscripts getSubs()
  {
    return subs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSubs(ArraySubscripts newSubs, NotificationChain msgs)
  {
    ArraySubscripts oldSubs = subs;
    subs = newSubs;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaPackage.COMPONENT_CLAUSE__SUBS, oldSubs, newSubs);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSubs(ArraySubscripts newSubs)
  {
    if (newSubs != subs)
    {
      NotificationChain msgs = null;
      if (subs != null)
        msgs = ((InternalEObject)subs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.COMPONENT_CLAUSE__SUBS, null, msgs);
      if (newSubs != null)
        msgs = ((InternalEObject)newSubs).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.COMPONENT_CLAUSE__SUBS, null, msgs);
      msgs = basicSetSubs(newSubs, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.COMPONENT_CLAUSE__SUBS, newSubs, newSubs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentList getComps()
  {
    return comps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetComps(ComponentList newComps, NotificationChain msgs)
  {
    ComponentList oldComps = comps;
    comps = newComps;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaPackage.COMPONENT_CLAUSE__COMPS, oldComps, newComps);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setComps(ComponentList newComps)
  {
    if (newComps != comps)
    {
      NotificationChain msgs = null;
      if (comps != null)
        msgs = ((InternalEObject)comps).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.COMPONENT_CLAUSE__COMPS, null, msgs);
      if (newComps != null)
        msgs = ((InternalEObject)newComps).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaPackage.COMPONENT_CLAUSE__COMPS, null, msgs);
      msgs = basicSetComps(newComps, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaPackage.COMPONENT_CLAUSE__COMPS, newComps, newComps));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ModelicaPackage.COMPONENT_CLAUSE__TYPE:
        return basicSetType(null, msgs);
      case ModelicaPackage.COMPONENT_CLAUSE__SUBS:
        return basicSetSubs(null, msgs);
      case ModelicaPackage.COMPONENT_CLAUSE__COMPS:
        return basicSetComps(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ModelicaPackage.COMPONENT_CLAUSE__PREFIX:
        return getPrefix();
      case ModelicaPackage.COMPONENT_CLAUSE__TYPE:
        return getType();
      case ModelicaPackage.COMPONENT_CLAUSE__SUBS:
        return getSubs();
      case ModelicaPackage.COMPONENT_CLAUSE__COMPS:
        return getComps();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ModelicaPackage.COMPONENT_CLAUSE__PREFIX:
        setPrefix((String)newValue);
        return;
      case ModelicaPackage.COMPONENT_CLAUSE__TYPE:
        setType((TypeSpecifier)newValue);
        return;
      case ModelicaPackage.COMPONENT_CLAUSE__SUBS:
        setSubs((ArraySubscripts)newValue);
        return;
      case ModelicaPackage.COMPONENT_CLAUSE__COMPS:
        setComps((ComponentList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ModelicaPackage.COMPONENT_CLAUSE__PREFIX:
        setPrefix(PREFIX_EDEFAULT);
        return;
      case ModelicaPackage.COMPONENT_CLAUSE__TYPE:
        setType((TypeSpecifier)null);
        return;
      case ModelicaPackage.COMPONENT_CLAUSE__SUBS:
        setSubs((ArraySubscripts)null);
        return;
      case ModelicaPackage.COMPONENT_CLAUSE__COMPS:
        setComps((ComponentList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ModelicaPackage.COMPONENT_CLAUSE__PREFIX:
        return PREFIX_EDEFAULT == null ? prefix != null : !PREFIX_EDEFAULT.equals(prefix);
      case ModelicaPackage.COMPONENT_CLAUSE__TYPE:
        return type != null;
      case ModelicaPackage.COMPONENT_CLAUSE__SUBS:
        return subs != null;
      case ModelicaPackage.COMPONENT_CLAUSE__COMPS:
        return comps != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (prefix: ");
    result.append(prefix);
    result.append(')');
    return result.toString();
  }

} //ComponentClauseImpl
