/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica.impl;

import org.eclipse.emf.ecore.EClass;

import xmodelica.modelica.ComponentDeclaration1;
import xmodelica.modelica.ModelicaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Component Declaration1</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComponentDeclaration1Impl extends ComponentClause1Impl implements ComponentDeclaration1
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComponentDeclaration1Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelicaPackage.Literals.COMPONENT_DECLARATION1;
  }

} //ComponentDeclaration1Impl
