/**
 * generated by Xtext 2.9.2
 */
package xmodelica.modelica.impl;

import org.eclipse.emf.ecore.EClass;

import xmodelica.modelica.ConnectClause;
import xmodelica.modelica.ModelicaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Connect Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConnectClauseImpl extends EquationImpl implements ConnectClause
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConnectClauseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelicaPackage.Literals.CONNECT_CLAUSE;
  }

} //ConnectClauseImpl
